//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:42:25 PM CET 
//


package project.a1.model.a1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.autorska_dela package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.autorska_dela
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AutorskoDelo }
     * 
     */
    public AutorskoDelo createAutorskoDelo() {
        return new AutorskoDelo();
    }

    /**
     * Create an instance of {@link ZahtevZaAutorskaDela }
     * 
     */
    public ZahtevZaAutorskaDela createZahtevZaAutorskaDela() {
        return new ZahtevZaAutorskaDela();
    }

    /**
     * Create an instance of {@link AutorskoDelo.Vrsta }
     * 
     */
    public AutorskoDelo.Vrsta createAutorskoDeloVrsta() {
        return new AutorskoDelo.Vrsta();
    }

    /**
     * Create an instance of {@link AutorskoDelo.FormatZapisa }
     * 
     */
    public AutorskoDelo.FormatZapisa createAutorskoDeloFormatZapisa() {
        return new AutorskoDelo.FormatZapisa();
    }

    /**
     * Create an instance of {@link IzvornoDelo }
     * 
     */
    public IzvornoDelo createIzvornoDelo() {
        return new IzvornoDelo();
    }

    /**
     * Create an instance of {@link Prilozi }
     * 
     */
    public Prilozi createPrilozi() {
        return new Prilozi();
    }

    /**
     * Create an instance of {@link TPreminuliAutor }
     * 
     */
    public TPreminuliAutor createTPreminuliAutor() {
        return new TPreminuliAutor();
    }

    /**
     * Create an instance of {@link TZivAutor }
     * 
     */
    public TZivAutor createTZivAutor() {
        return new TZivAutor();
    }

}
