//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:42:25 PM CET 
//


package project.a1.model.a1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TFormat_zapisa.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TFormat_zapisa">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="opticki_disk"/>
 *     &lt;enumeration value="stampani_tekst"/>
 *     &lt;enumeration value="ostalo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TFormat_zapisa")
@XmlEnum
public enum TFormatZapisa {

    @XmlEnumValue("opticki_disk")
    OPTICKI_DISK("opticki_disk"),
    @XmlEnumValue("stampani_tekst")
    STAMPANI_TEKST("stampani_tekst"),
    @XmlEnumValue("ostalo")
    OSTALO("ostalo");
    private final String value;

    TFormatZapisa(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TFormatZapisa fromValue(String v) {
        for (TFormatZapisa c: TFormatZapisa.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
