//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:44:33 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/sema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package project.xml.main_schema;
