//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:44:33 PM CET 
//


package project.xml.z1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import project.xml.main_schema.TLice;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/sema}Podnosilac_prijave"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/sema}Punomocnik"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/z}Zig"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/z}Takse"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/z}Prilozi"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilacPrijave",
    "punomocnik",
    "zig",
    "takse",
    "prilozi"
})
@XmlRootElement(name = "Zahtev_za_zig")
public class ZahtevZaZig {

    @XmlElement(name = "Podnosilac_prijave", namespace = "http://ftn.uns.ac.rs/sema", required = true)
    protected TLice podnosilacPrijave;
    @XmlElement(name = "Punomocnik", namespace = "http://ftn.uns.ac.rs/sema", required = true)
    protected TLice punomocnik;
    @XmlElement(name = "Zig", required = true)
    protected Zig zig;
    @XmlElement(name = "Takse", required = true)
    protected Takse takse;
    @XmlElement(name = "Prilozi", required = true)
    protected Prilozi prilozi;

    /**
     * Gets the value of the podnosilacPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPodnosilacPrijave() {
        return podnosilacPrijave;
    }

    /**
     * Sets the value of the podnosilacPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPodnosilacPrijave(TLice value) {
        this.podnosilacPrijave = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPunomocnik(TLice value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the zig property.
     * 
     * @return
     *     possible object is
     *     {@link Zig }
     *     
     */
    public Zig getZig() {
        return zig;
    }

    /**
     * Sets the value of the zig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zig }
     *     
     */
    public void setZig(Zig value) {
        this.zig = value;
    }

    /**
     * Gets the value of the takse property.
     * 
     * @return
     *     possible object is
     *     {@link Takse }
     *     
     */
    public Takse getTakse() {
        return takse;
    }

    /**
     * Sets the value of the takse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Takse }
     *     
     */
    public void setTakse(Takse value) {
        this.takse = value;
    }

    /**
     * Gets the value of the prilozi property.
     * 
     * @return
     *     possible object is
     *     {@link Prilozi }
     *     
     */
    public Prilozi getPrilozi() {
        return prilozi;
    }

    /**
     * Sets the value of the prilozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prilozi }
     *     
     */
    public void setPrilozi(Prilozi value) {
        this.prilozi = value;
    }

}
