//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:42:25 PM CET 
//


package project.xml.a1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import project.xml.main_schema.TPrilog;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Opis_dela" type="{http://ftn.uns.ac.rs/sema}TPrilog"/>
 *         &lt;element name="Primer_dela" type="{http://ftn.uns.ac.rs/sema}TPrilog"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opisDela",
    "primerDela"
})
@XmlRootElement(name = "Prilozi")
public class Prilozi {

    @XmlElement(name = "Opis_dela", required = true)
    protected TPrilog opisDela;
    @XmlElement(name = "Primer_dela", required = true)
    protected TPrilog primerDela;

    /**
     * Gets the value of the opisDela property.
     * 
     * @return
     *     possible object is
     *     {@link TPrilog }
     *     
     */
    public TPrilog getOpisDela() {
        return opisDela;
    }

    /**
     * Sets the value of the opisDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrilog }
     *     
     */
    public void setOpisDela(TPrilog value) {
        this.opisDela = value;
    }

    /**
     * Gets the value of the primerDela property.
     * 
     * @return
     *     possible object is
     *     {@link TPrilog }
     *     
     */
    public TPrilog getPrimerDela() {
        return primerDela;
    }

    /**
     * Sets the value of the primerDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrilog }
     *     
     */
    public void setPrimerDela(TPrilog value) {
        this.primerDela = value;
    }

}
