//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:44:33 PM CET 
//


package project.xml.z1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Graficko_resenje" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Ukupno" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Klase">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>positiveInteger">
 *                 &lt;attribute name="Broj_klasa">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                       &lt;maxInclusive value="45"/>
 *                       &lt;minInclusive value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "osnovnaTaksa",
    "grafickoResenje",
    "ukupno",
    "klase"
})
@XmlRootElement(name = "Takse")
public class Takse {

    @XmlElement(name = "Osnovna_taksa", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger osnovnaTaksa;
    @XmlElement(name = "Graficko_resenje", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger grafickoResenje;
    @XmlElement(name = "Ukupno", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ukupno;
    @XmlElement(name = "Klase", required = true)
    protected Takse.Klase klase;

    /**
     * Gets the value of the osnovnaTaksa property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOsnovnaTaksa() {
        return osnovnaTaksa;
    }

    /**
     * Sets the value of the osnovnaTaksa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOsnovnaTaksa(BigInteger value) {
        this.osnovnaTaksa = value;
    }

    /**
     * Gets the value of the grafickoResenje property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrafickoResenje() {
        return grafickoResenje;
    }

    /**
     * Sets the value of the grafickoResenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrafickoResenje(BigInteger value) {
        this.grafickoResenje = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUkupno(BigInteger value) {
        this.ukupno = value;
    }

    /**
     * Gets the value of the klase property.
     * 
     * @return
     *     possible object is
     *     {@link Takse.Klase }
     *     
     */
    public Takse.Klase getKlase() {
        return klase;
    }

    /**
     * Sets the value of the klase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Takse.Klase }
     *     
     */
    public void setKlase(Takse.Klase value) {
        this.klase = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>positiveInteger">
     *       &lt;attribute name="Broj_klasa">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *             &lt;maxInclusive value="45"/>
     *             &lt;minInclusive value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Klase {

        @XmlValue
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger value;
        @XmlAttribute(name = "Broj_klasa")
        protected Integer brojKlasa;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the brojKlasa property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBrojKlasa() {
            return brojKlasa;
        }

        /**
         * Sets the value of the brojKlasa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBrojKlasa(Integer value) {
            this.brojKlasa = value;
        }

    }

}
