//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:44:33 PM CET 
//


package project.z1.model.z1;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Graficko_resenje" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Ukupno" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Klase">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>positiveInteger">
 *                 &lt;attribute name="Broj_klasa">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                       &lt;maxInclusive value="45"/>
 *                       &lt;minInclusive value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "osnovnaTaksa",
    "grafickoResenje",
    "ukupno",
    "klase",
        "brojKlasa"
})
@XmlRootElement(name = "Takse")
public class Takse {

    @XmlElement(name = "Osnovna_taksa", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger osnovnaTaksa;
    @XmlElement(name = "Graficko_resenje", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger grafickoResenje;
    @XmlElement(name = "Ukupno", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ukupno;
    @XmlElement(name = "Klase", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger klase;

    @XmlElement(name = "Broj_klasa", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojKlasa;

    public BigInteger getBrojKlasa() {
        return brojKlasa;
    }

    public void setBrojKlasa(BigInteger brojKlasa) {
        this.brojKlasa = brojKlasa;
    }

    public BigInteger getKlase() {
        return klase;
    }

    public void setKlase(BigInteger klase) {
        this.klase = klase;
    }

    /**
     * Gets the value of the osnovnaTaksa property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOsnovnaTaksa() {
        return osnovnaTaksa;
    }

    /**
     * Sets the value of the osnovnaTaksa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOsnovnaTaksa(BigInteger value) {
        this.osnovnaTaksa = value;
    }

    /**
     * Gets the value of the grafickoResenje property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrafickoResenje() {
        return grafickoResenje;
    }

    /**
     * Sets the value of the grafickoResenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrafickoResenje(BigInteger value) {
        this.grafickoResenje = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUkupno(BigInteger value) {
        this.ukupno = value;
    }


}
