//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:44:33 PM CET 
//


package project.z1.model.z1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TVrsta_znaka.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TVrsta_znaka">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="verbalni"/>
 *     &lt;enumeration value="graficki"/>
 *     &lt;enumeration value="kombinovani"/>
 *     &lt;enumeration value="trodimenzionalni"/>
 *     &lt;enumeration value="ostalo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TVrsta_znaka")
@XmlEnum
public enum TVrstaZnaka {

    @XmlEnumValue("verbalni")
    VERBALNI("verbalni"),
    @XmlEnumValue("graficki")
    GRAFICKI("graficki"),
    @XmlEnumValue("kombinovani")
    KOMBINOVANI("kombinovani"),
    @XmlEnumValue("trodimenzionalni")
    TRODIMENZIONALNI("trodimenzionalni"),
    @XmlEnumValue("ostalo")
    OSTALO("ostalo");
    private final String value;

    TVrstaZnaka(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TVrstaZnaka fromValue(String v) {
        for (TVrstaZnaka c: TVrstaZnaka.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
