//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.12 at 03:44:33 PM CET 
//


package project.z1.model.z1;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Izgled_znaka" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Boja" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="Transliteracija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Prevod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Klasa_robe" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="45"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Tip_ziga" type="{http://ftn.uns.ac.rs/z}TTip_ziga" />
 *       &lt;attribute name="Vrsta_znaka" type="{http://ftn.uns.ac.rs/z}TVrsta_znaka" />
 *       &lt;attribute name="Ostalo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "izgledZnaka",
    "boja",
    "transliteracija",
    "prevod",
    "opis",
    "klasaRobe"
})
@XmlRootElement(name = "Zig")
public class Zig {

    @XmlElement(name = "Izgled_znaka", required = true)
    protected Object izgledZnaka;
    @XmlElement(name = "Boja", required = true)
    protected List<String> boja;
    @XmlElement(name = "Transliteracija", required = true)
    protected String transliteracija;
    @XmlElement(name = "Prevod", required = true)
    protected String prevod;
    @XmlElement(name = "Opis", required = true)
    protected String opis;
    @XmlElement(name = "Klasa_robe", type = Integer.class)
    protected List<Integer> klasaRobe;
    @XmlAttribute(name = "Tip_ziga")
    protected TTipZiga tipZiga;
    @XmlAttribute(name = "Vrsta_znaka")
    protected TVrstaZnaka vrstaZnaka;
    @XmlAttribute(name = "Ostalo")
    protected String ostalo;

    /**
     * Gets the value of the izgledZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIzgledZnaka() {
        return izgledZnaka;
    }

    /**
     * Sets the value of the izgledZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIzgledZnaka(Object value) {
        this.izgledZnaka = value;
    }

    /**
     * Gets the value of the boja property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boja property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoja().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBoja() {
        if (boja == null) {
            boja = new ArrayList<String>();
        }
        return this.boja;
    }

    /**
     * Gets the value of the transliteracija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransliteracija() {
        return transliteracija;
    }

    /**
     * Sets the value of the transliteracija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransliteracija(String value) {
        this.transliteracija = value;
    }

    /**
     * Gets the value of the prevod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevod() {
        return prevod;
    }

    /**
     * Sets the value of the prevod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevod(String value) {
        this.prevod = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the klasaRobe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the klasaRobe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKlasaRobe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getKlasaRobe() {
        if (klasaRobe == null) {
            klasaRobe = new ArrayList<Integer>();
        }
        return this.klasaRobe;
    }

    /**
     * Gets the value of the tipZiga property.
     * 
     * @return
     *     possible object is
     *     {@link TTipZiga }
     *     
     */
    public TTipZiga getTipZiga() {
        return tipZiga;
    }

    /**
     * Sets the value of the tipZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTipZiga }
     *     
     */
    public void setTipZiga(TTipZiga value) {
        this.tipZiga = value;
    }

    /**
     * Gets the value of the vrstaZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link TVrstaZnaka }
     *     
     */
    public TVrstaZnaka getVrstaZnaka() {
        return vrstaZnaka;
    }

    /**
     * Sets the value of the vrstaZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVrstaZnaka }
     *     
     */
    public void setVrstaZnaka(TVrstaZnaka value) {
        this.vrstaZnaka = value;
    }

    /**
     * Gets the value of the ostalo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOstalo() {
        return ostalo;
    }

    /**
     * Sets the value of the ostalo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOstalo(String value) {
        this.ostalo = value;
    }

}
